 --Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender


--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount 
from customer 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)


-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, 
ROUND(AVG(purchase_am…
[6:16 pm, 12/01/2026] Vipul: --Q1. Total revenue generated by male vs. female customers
SELECT "Gender", SUM("Purchase Amount (USD)") AS revenue
FROM customer
GROUP BY "Gender";

--Q2. Customers with discount who spent more than average
SELECT "Customer ID", "Purchase Amount (USD)" 
FROM customer 
WHERE "Discount Applied" = 'Yes' 
AND "Purchase Amount (USD)" >= (SELECT AVG("Purchase Amount (USD)") FROM customer);

--Q3. Top 5 products with highest average review rating
SELECT "Item Purchased", ROUND(AVG("Review Rating"::numeric), 2) AS "Average Product Rating"
FROM customer
GROUP BY "Item Purchased"
ORDER BY "Average Product Rating" DESC
LIMIT 5;

--Q4. Average Purchase Amounts between Standard and Express Shipping
SELECT "Shipping Type", ROUND(AVG("Purchase Amount (USD)"), 2) AS "Avg P…
[6:20 pm, 12/01/2026] Vipul: --Q1. Total revenue by Gender
SELECT "Gender", SUM("Purchase Amount (USD)") AS revenue
FROM customer
GROUP BY "Gender";

--Q2. Discount users spending more than average
SELECT "Customer ID", "Purchase Amount (USD)" 
FROM customer 
WHERE "Discount Applied" = 'Yes' 
AND "Purchase Amount (USD)" >= (SELECT AVG("Purchase Amount (USD)") FROM customer);

--Q3. Top 5 products with highest average review rating
SELECT "Item Purchased", ROUND(AVG("Review Rating"::numeric), 2) AS "Average Product Rating"
FROM customer
GROUP BY "Item Purchased"
ORDER BY "Average Product Rating" DESC
LIMIT 5;

--Q4. Average Purchase Amounts between Standard and Express Shipping
SELECT "Shipping Type", ROUND(AVG("Purchase Amount (USD)"), 2) AS "Avg Purchase"
FROM customer
WHERE "Shipping Type" IN ('Standard', 'Express')
GROUP BY "Shipping Type";

--Q5. Subscribers vs Non-subscribers comparison
SELECT "Subscription Status",
       COUNT("Customer ID") AS total_customers,
       ROUND(AVG("Purchase Amount (USD)"), 2) AS avg_spend,
       ROUND(SUM("Purchase Amount (USD)"), 2) AS total_revenue
FROM customer
GROUP BY "Subscription Status"
ORDER BY total_revenue DESC;

--Q6. Top 5 products with highest discount percentage
SELECT "Item Purchased",
       ROUND(100.0 * SUM(CASE WHEN "Discount Applied" = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate
FROM customer
GROUP BY "Item Purchased"
ORDER BY discount_rate DESC
LIMIT 5;

--Q7. Customer Segmentation (New, Returning, Loyal)
WITH customer_type AS (
    SELECT "Customer ID", "Previous Purchases",
    CASE 
        WHEN "Previous Purchases" <= 1 THEN 'New'
        WHEN "Previous Purchases" BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment
    FROM customer
)
SELECT customer_segment, COUNT(*) AS "Number of Customers" 
FROM customer_type 
GROUP BY customer_segment;

--Q8. Top 3 most purchased products within each category
WITH item_counts AS (
    SELECT "Category",
           "Item Purchased",
           COUNT("Customer ID") AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY "Category" ORDER BY COUNT("Customer ID") DESC) AS item_rank
    FROM customer
    GROUP BY "Category", "Item Purchased"
)
SELECT item_rank, "Category", "Item Purchased", total_orders
FROM item_counts
WHERE item_rank <= 3;

--Q9. Repeat buyers and subscription status
SELECT "Subscription Status",
       COUNT("Customer ID") AS repeat_buyers
FROM customer
WHERE "Previous Purchases" > 5
GROUP BY "Subscription Status";

--Q10. Revenue contribution by Age
-- Note: Aapke table mein column ka naam sirf "Age" hai.
SELECT 
    "Age",
    SUM("Purchase Amount (USD)") AS total_revenue
FROM customer
GROUP BY "Age"
ORDER BY total_revenue DESC;